name: Android CI Build

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache gradle directories
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            ./.gradle
          key: gradle-${{ hashFiles('gradle/wrapper/**') }}

      - name: Cache android build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.android
            ./build
            ./**/build
          key: android-${{ github.sha }}

      - run: env

      - run: ls ${ANDROID_SDK_ROOT}/licenses

      - run:  ./gradlew --no-daemon build
